version: '5'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - "27017:27017"
  springdockercompose:
    image: springdockercompose:latest
    container_name: springdockercompose
    ports:
      - "8087:6000"
    links:
      - mongodb